# Generated by Django 3.2.7 on 2021-10-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(limit_choices_to={'user_type': 'student'}, related_name='classrooms_studying', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_datetime'],
                'unique_together': {('name', 'teacher')},
            },
        ),
    ]
