# Generated by Django 3.2.7 on 2021-10-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.PositiveSmallIntegerField()),
                ('to_number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True/False/Not given'), ('yes_no', 'Yes/No/Not given'), ('fill_blank', 'Fill in the blank')], max_length=30)),
                ('correct_answer', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.readingexercise')),
            ],
            options={
                'ordering': ['exercise', 'from_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(blank=True, max_length=1)),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.readingquestion')),
            ],
            options={
                'ordering': ['question', 'letter', 'pk'],
            },
        ),
    ]
