# Generated by Django 3.2.7 on 2021-10-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_readinganswer_readingexercise_readingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingexercise',
            name='classrooms',
            field=models.ManyToManyField(related_name='reading_exercises', to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='readingexercise',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_exercises_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
