# Generated by Django 3.2.7 on 2021-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_readingexercise_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinganswer',
            name='letter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / False / Not given'), ('yes_no', 'Yes / No / Not given'), ('fill_blank', 'Fill in the blank')], max_length=30),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='to_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
