# Generated by Django 3.2.7 on 2021-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20211004_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='passage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
