# Generated by Django 3.2.7 on 2021-10-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20211005_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingquestion',
            options={'ordering': ['exercise']},
        ),
        migrations.RenameField(
            model_name='readingquestion',
            old_name='from_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='to_number',
        ),
        migrations.CreateModel(
            name='ReadingCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='classroom.readingquestion')),
            ],
            options={
                'ordering': ['content'],
            },
        ),
    ]
