# Generated by Django 3.2.7 on 2021-10-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20211005_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['content'],
            },
        ),
        migrations.RenameField(
            model_name='readingquestion',
            old_name='answers',
            new_name='choices',
        ),
        migrations.DeleteModel(
            name='ReadingCorrectAnswer',
        ),
        migrations.AddField(
            model_name='readinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.readingquestion'),
        ),
    ]
