# Generated by Django 3.2.7 on 2021-10-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0010_remove_readingquestion_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.readingexercise')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exercise', 'submitter'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('content', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='classroom.readingsubmission')),
            ],
            options={
                'ordering': ['submission', 'question_number'],
            },
        ),
    ]
