# Generated by Django 3.2.7 on 2021-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_readingsubmission_readingsubmissionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingsubmission',
            options={'ordering': ['exercise', 'submitter', 'submit_datetime']},
        ),
        migrations.AlterField(
            model_name='readingsubmission',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
