# Generated by Django 3.2.7 on 2021-10-06 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0012_auto_20211006_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingsubmission',
            unique_together={('exercise', 'submitter')},
        ),
    ]
