# Generated by Django 3.2.7 on 2021-10-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_alter_readingsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingquestion',
            options={'ordering': ['exercise', 'number']},
        ),
    ]
