# Generated by Django 3.2.7 on 2021-10-23 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_readingquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsubmission',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
